---
title: "R Notebook"
output: html_notebook
---

DATA SCIENCE PROGRAMMING II (BSD2223)

LAB REPORT 3
NAME:         TEAN JIN HE
MATRIC ID:    SD21063
SECTION:      01G

QUESTIONS 1
```{r}
#a.
#The main characteristics of list data structure are the list is a generic object consisting of an ordered collection of objects. Next, the list can contain elements of different data types, such as vectors, matrices, characters, functions and others. Other than that, the list can be accessed by names or indices using the dollar ($) operator or the double slicing operator ([[]]) and can be a parent class for other data structures, such as data.frame.

#b.
#Two functions from family of apply(.) functions which can be used for lists are:

#1.lapply(): This function applies the function to each element of the list and returns the list as a result.

#2.sapply(): This function is similar to lapply(), but it tries to simplify the output by returning a vector or matrix instead of the list.
```

Questions 2
```{r}
#a.
l1 <- seq(-10 ,10, length.out=25)
m1 <- matrix(c(TRUE,FALSE,FALSE,TRUE,TRUE,FALSE,TRUE,FALSE, TRUE,FALSE,FALSE,FALSE,TRUE,FALSE,TRUE,TRUE), nrow = 4)
v1 <- c("apple", "banana", "kiwi", "watermelon")
v2 <- c("low", "medium", "medium", "low", "high", "low")
list1 <- list(l1,m1,v1,v2)
list1
```
```{r}
#b.
names(list1) <- c("Sequence","Matrix","Character","Character")
list1
```
```{r}
#c.
list1[[2]][c(3, 1), c(3, 4)]
```
```{r}
#d.
round(list1[[1]][list1[[1]] > -0.5 & list1[[1]] < 7], digits = 2)
```

```{r}
#e.
list1[[4]][list1[[4]] == "medium"] <- "low"
list1[[4]]
```

