---
title: "R Notebook"
output: html_notebook
---
Exercise 7

Question b
```{r}
load(file="dt_clean.RData")
dt1_clean
```
Question c
```{r}
dt1_clean$height 
```
Question d
```{r}
## by default right value inclusive

lbs <- c("height<1.5", "1.5<height<1.6", "height>1.6")
height_group <- cut(dt1_clean$height, breaks = c(0,1.5,1.6,Inf),labels=lbs)
height_group

levels(height_group) ## number of group
```
```{r}
## combine weight data with group
cbind(dt1_clean$height,height_group)
```
Question e
```{r}
## frequency in each group
table(height_group)

OR

## Using factor
f_height_group <- factor(height_group, levels=c("height<1.5", "1.5<height<1.6", "height>1.6"),ordered=TRUE)
table(f_height_group)
```
```{r}
#freq. table of proportions for height variable
prop.table(table(height_group))
```

Question f
```{r}
## 2-way freq. table (by Section)
table(dt1_clean$Section, height_group)

##2-way freq. table (by gender)
table(dt1_clean$Gender, height_group)
```

