---
title: "R Notebook"
output: html_notebook
---

Exercise 4

Question a
```{r}
C_degree <- function(F) (5/9)*(F-32)
C_degree
```
Question b
```{r}

F <- c(47,80,25,20,105,132,30,274,33,214,58,77)

vC <- sapply(F, C_degree)
round(vC, 2)
```
Exercise 5

```{r}
A <- c(2,1,-3)
B <- c(1,4,0,3,2,8)
C <- c(1,4,0,3,2,8,-1,5,0)
MatrixA <- matrix(A, nrow = 3, ncol = 1); MatrixA
MatrixB <- matrix(B, nrow = 3, ncol = 2); MatrixB
MatrixC <- matrix(C, nrow = 3, ncol = 3); MatrixC
```
Question a
```{r}
# 5a (3x1) != (3x2)
MatrixA %*% MatrixB
```
Question b
```{r}
t(MatrixA) %*% MatrixB
```
Question c
```{r}
t(MatrixB) %*% (MatrixA %*% t(MatrixA))
```
Question d
```{r}
(MatrixA %*% t(MatrixA)) %*% t(MatrixB)
```
```{r}
# 5e
((MatrixB %*% t(MatrixB))+(MatrixA %*% t(MatrixA))-(10/3))**-1
```
Exercise 6

Question a
```{r}
v1 <- seq(5.5,0.5)
Array1 <- array(v1, dim = c(4,2,6)); Array1
```
Question b
```{r}
Array1[3,2,4]
```
Question c
```{r}
Array1[2,,1]
```

