---
title: "R Notebook"
output: html_notebook
---

chapter 3 matrix
3.1 Create matrix
```{r}
## create numeric matrix
m1 <- matrix(1:12, nrow= 3); m1
m2 <- matrix(1:12, nrow= 3, ncol=4); m2
m3 <- matrix(1:12, nrow= 3, byrow=TRUE); m3
## create string matrix
m4 <- matrix(c("a", "b","c","d","e","f"), nrow= 3); m4
## naming rows and columns of a matrix
m1 <- matrix(1:12, nrow= 3,
dimnames = list(c("A","B","C"), c("D","E","F","G")))
m1
rownames(m1)
colnames(m1)
```
3.2
```{r}
#(i) Create matrix using rbind(.) or cbind(.)
c1 <- 1:6
c2 <- 7:12
cbind(c1,c2) #column bind
rbind(c1,c2) #row bind

#(ii) Create matrix using dim(.)
m5 <- 5:19
dim(m5) <- c(5,3) # 5 rows x 3 columns
m5

#(iii) Special matrix - identity matrix
diag(5) ##create identity matrix of 5 by 5
m7 <- matrix(-10:10, nrow=5); m7
diag(m7) ##extract diagonal elements
```
test
```{r}
#1.create 5*5 matrix , assign a name
mx <- matrix(1:25,nrow=5, ncol=5)
mx

#2.name the rows and columns
mx1 <- matrix(mx,nrow=5,dimnames = list(c("A","B","C","D","E"), c("F","G","H","I","J")))
mx1

#3.identify matrix entry of[2,3]
mx1[2,3]

#4.create another matrix of 2*5 for even series
mat<-seq(2,20,by=2)
m6<-matrix(mat, nrow = 2, ncol = 5);m6
```

3.3
```{r}
# construct 3 by 2 matrix with labels
dt <- c(1,26,24,68,10,15)
rnames <- c("R1", "R2","R3")
cnames <- c("C1", "C2")
mt1 <- matrix(dt, nrow=3, ncol=2,
dimnames=list(rnames, cnames))
mt1
mt2 <- matrix(15:18, nrow = 2,
dimnames = list(c("P","Q"), c("A","B")))
mt2
# create identity matrix and extract diagonal element
diag(4)
diag(mt2)
diag(3,4)
```
3.4 matrix operation
```{r}
A <- matrix(data = 1:16, nrow = 4, ncol = 4,
byrow = TRUE); A
B <- matrix(data = 16:31, nrow = 4, ncol = 4,
byrow = FALSE); B
A + B
A - B
A * B
A/B
# Matrix Algebra
5*A # scalar multiplication
A %*% B # matrix multiplication
B %*% t(A)

#inverse matrix
t(A)
a1 <-matrix(c(1,2,3,4),nrow=2)
a1
det(a1)
solve(a1)
```
3.5 inverse matrix
```{r}
# Create 3 different vectors.
a1 <- c(3, 2, 8)
a2 <- c(6, 3, 2)
a3 <- c(5, 2, 4)

# Bind the 3 matrices row-wise: rbind(.)
A <- rbind(a1, a2, a3)
det(A) ## determinant matrix A must not zero

#inverse matrix
# Find inverse of a matrix using inv(.) function
# install.packages("matlib")
library(matlib)

# find inverse using the solve() function.
solve(A)

A %*% solve(A)

A %*% inv(A)

A_inv <- round(inv(A))
A_inv


# Create 3 different vectors.
b1 <- c(1, 2, 5)
b2 <- c(7, 4, 1)
b3 <- c(1, 9, 0)
# Bind the 3 matrices row-wise: rbind(.)
B <- rbind(b1, b2, b3)
det(B) ## determinant matrix A must not zero
# find inverse using the inv() function.
inv(B)

B_inv <- round(inv(B))
B_inv

B %*% B_inv
```

3.5 subset a matrix
```{r}
## Subset a matrix
m6 <- c(3, 5, -7, 18, 0, 0.5, 1, 9, 6)
dim(m6) <- c(3,3)
m6
```
```{r}
m6[1:2,] #select row 1&2 and all columns
m6[c(1,3),2] #select row 1&3 and column 2
m6[c(1,3),c(1,2)] #select row 1&3 and column 1&2
m6[-1,] #select all except row 1
```

3.6 add or delete elements of matrix
```{r}
mat <- matrix(c(0, -4.5, 57, 68, 0.1, 107, -0.5, 10.8, 3.4), nrow=3)
mat
mat[,-3] ##delete 3rd column
mat[-1, 3:2] ##delete 1st row and rearrange row 2&3
mat[-2, -c(1,3)] ##delete 2nd row and column 1&3
tam <- mat ##rename the matrix
tam
tam[3,] <- 2:4 ##replace row 3 with 2,3,4
tam
tam[c(1,2),3] <- 999 ##replace row 1&2 and col 3 with 999
tam
```
3.7 array
```{r}
## Array
## Form a matrix of 3 by 4 for 2 layers
ar1 <- array(1:24, dim= c(3,4,2))
ar1
```
```{r}
## Form a matrix of 3 by 4 for 2 layers and 2 sets
ar2 <- array(rep(1:24, times=3), dim= c(3,4,2,2))
ar2
```
```{r}
## Form a matrix of 3 by 4 for 2 layers and 3 sets
ar3 <- array(rep(1:24, times=3), dim= c(3,4,2,3))
ar3
```

3.8
```{r}
## Array
## Form a matrix of 3 by 4 for 2 layers
ar1 <- array(1:24, dim= c(3,4,2))
ar1
## Form a matrix of 3 by 4 for 2 layers and 2 sets
ar2 <- array(rep(1:24, times=3), dim= c(3,4,2,2))
ar2
## Form a matrix of 3 by 4 for 2 layers and 3 sets
ar3 <- array(rep(1:24, times=3), dim= c(3,4,2,3))
ar3
```
3.9 Erray
```{r}
## create an array from 2 matrices of 3 by 3
v1 <- c(3,0,1)
v2 <- c(5,23,19,42,10,-5)

## create an array from 2 matrices of 3 by 3
ar1 <- array(c(v1,v2),dim = c(3,3,2)); ar1

## Name the matrix rows and columns
column.names <- c("COL1","COL2","COL3")
row.names <- c("ROW1","ROW2","ROW3")
matrix.names <- c("Matrix1","Matrix2")
ar2 <- array(c(v1,v2),dim = c(3,3,2),
dimnames = list(row.names,column.names,
matrix.names))
ar2

## Extract elements from the array
ar2[3]
ar2[2,,2] ## element of row 2 of matrix 2
ar2[2,3,1] ## element of row 2, column 3 of matrix 1
ar2[,,2] ## matrix 2

```

testing
```{r}
#constraint anarrau of dim=4,4,2
v1 <- c(2,0,1,4,8,3)
v2 <- c(5,2,8,7,4,3)
ar1 <- array(c(v1,v2),dim = c(4,4,2));
ar1

```
3.11
```{r}
## Operation on Arrays
## Create 2 arrays
v3 <- 1:4
v4 <- c(1,5,11,10,6,12,-5,0,8,7,9,2)
ar3 <- array(c(v3,v4),dim = c(4,4,2)); ar3
v5 <- rep(2,8)
v6 <- seq(2,6, length=9)
ar4 <- array(c(v5,v6),dim = c(4,4,2)); ar4

## create matrix from array and sum the matrices
m1 <- ar3[,,1]
m1
m2 <- ar4[,,1]
m2

m1+m2

```

3.12
```{r}
## Array
## Form a matrix of 3 by 4 for 2 layers
ar1 <- array(1:24, dim= c(3,4,2))
ar1
## Form an array
## Form a matrix of 3 by 4 for 2 layers and 2 sets
ar2 <- array(rep(1:24, times=3), dim= c(3,4,2,2))
ar2
## Form a matrix of 3 by 4 for 2 layers and 3 sets
ar3 <- array(rep(1:24, times=3), dim= c(3,4,2,3))
ar3
```

3.13
```{r}
##Syntax: apply(x, margin, fun)
## apply(.) Function
v5 <- rep(2,8)
v5
v6 <- seq(2,6, length=8)
v6
ar4 <- array(c(v5,v6),dim = c(4,4,2)); ar4
# fun = sum
apply(ar4, c(1), sum) #c(1) sum through rows
apply(ar4, c(2), sum) #c(2) sum through columns
# fun = mean
apply(ar4, c(1), mean) #c(1) mean through rows
apply(ar4, c(2), mean) #c(2) mean through columns
```

