---
title: "R Notebook"
output: html_notebook
---
2.1 Vectors
```{r}
# numeric
x <- 10.5
class(x)
# integer
x <- 1000L
class(x)
# complex
x <- 9i + 3
class(x)
# character/string
x <- "R is exciting"
class(x)
# logical/boolean
x <- TRUE
```
2.2
```{r}
# repeat a value
rep(7,times=5)
# repeat a vector
rep(1:3,times=10)
v <- c(1,2,3)
rep(v,times=3)
## insert an element into the middle of a vector
append(2:30, 77, after=5) # Insert 77 after 5th element
# Turn numerical vector to character
v <- c(0, 1, 14, -1, 4, 0.5)
as.vector(v, mode="character")
# Turn numerical vector to logical
v <- c(0, 1, -2, TRUE, FALSE)
as.vector(v, mode="logical")
```
2.3
```{r}
## Create vectors
id.no <- c(21001, 20014, 20045, 21004); id.no
new.id.no <- as.character(id.no); new.id.no
class(id.no); class(new.id.no)
myname <- c("Diana", "Devina", "Chong", "Hani"); myname
class(myname)
## c(.) concatenate
v1 <- c(1,2,3,4,5,6,7,8,9,10); v1
## : (colon) operator
v2 <- 1:10; v2
## seq(.)
v3 <- seq(1,10, by=1); v3
v4 <- seq(-100,100, by=.5); v4
```
2.4
```{r}
x <- c(5.5, -10, 1/2, 8, sqrt(6)); x
y <- c("I","like","R"); y
z <- c(FALSE,TRUE,FALSE,FALSE,TRUE,TRUE); z
## Mixed vector types will become character vector
p <- c("Data science", 4:8, FALSE, TRUE); p
## component extraction
z1 <- seq(2,20, by=2)
length(z1) # number of element in x
z1[4] # the fourth element
z1[1:3] # the first three elements in z
z1[-2] # except the second element
z1[z > 2] # list of element in z greater than 2

## Create Letters
LETTERS[seq( from = 1, to = 26 )]
letters[seq( from = 1, to = 26 )]
LETTERS[c(5,15,23)]
```
2.5(a) Vector Operation
```{r}
## 1. Combining vectors
v1 <- 1:5
v2 <- c("Hadoop", "Spark", "HIVE", "Flink", "Shiny")
c(v1,v2)
## 2. Airthmetic Operation on R
v1 <- c(3,15, 0)
v2 <- c(4, 23,0)
v1 + v2 # Addition
v2 - v1 # Subtraction
v1/v2 # division
v2 %% v1 # remainder
v2 %/% v1 # quotient
```
2.5(b) Vector Operation
```{r}
## 3. Numeric Index
v3 <- c("a", "b", "c", "d", "e") #Creating our vector
v3[5] ## vector position
v3[-c(3:6)] ## all vectors except
v3[6] ## out of range
## 4. Duplicate Index
v2 <- c("Hadoop", "Spark", "HIVE", "Flink", "Shiny")
v2[c(2,1,3,5,5,5)]
## 5. Range Indexes
v2 <- c("Hadoop", "Spark", "HIVE", "Flink", "Shiny")
v2[3:5]
```
2.5(c)
```{r}
## 6. Out-of-order Indexes
v2 <- c("Hadoop", "Spark", "HIVE", "Flink", "Shiny")
v2[c(1:3, 6)]
## 7. Named Vectors Members
v3 <- c("Python", "R", "SAS", "Java")
names(v3) <- c("First", "Second", "Third", "Fourth")
v3
v3["Second"]

```
2.6
```{r}
x <- c(2,4,8,10)
is.na(x) #logical vector
x_na <- c(2,4,NA,8,10,NA)
is.na(x_na) #logical vector
which(is.na(x_na)) #numeric vector
sum(is.na(x_na)) #the number of NAs in x
sum(!is.na(x_na)) #the number of non-NAs in x
```
2.7
```{r}
## Data with NA values
v4 <- c(99, 50, NA, 17, 100)
mean(v4)
mean(v4, na.rm = TRUE)
## Data with NULL values
## NULL isn’t a problem, because it doesn’t exist
v5 <- c(99, 50, NULL, 17, 100)
mean(v5)
vx <- c(4,5, 8, NULL, 36)
vx
sum(vx)
## Data with NaN values
vz <- c(4,5, 8, NaN, 5)
sum(vz)
sum(vz, na.rm=TRUE)
```
2.8(a)
```{r}
# Create a vector
x1 <- c(5:9, NA, 1:4, NA); x1
is.na(x1)
anyNA(x1)
which(is.na(x1))
sum(is.na(x1))
# Create a data frame
df <- data.frame(x2 <- c(NA, 5:8),
x3 <- c("L", "a", "T", "e", "X"),
x4 <- c(1+5i, 2-3i, NA, NA, 3.5),
x5 <- c(TRUE, FALSE, NA, TRUE, FALSE))
names(df) <- c("No.","Letters","Complex","Logical")
df
is.na(df)
is.na(df$Complex)
colSums(is.na(df))

```
2.8(b)
```{r}
y1 <- c(5:9, NA, 10.4, 20.5, NA); y1
# replace missing values with the mean of the data
y1[is.na(y1)] <- mean(y1, na.rm=TRUE); round(y1,2)
# code missing values as 99
df2 <- data.frame(x2 <- c(NA, 5, 10, 105, 99),
x3 <- c("L", "a", "T", "e", "X"),
x4 <- c(1+5i, 2-3i, NA, NA, 3.5),
x5 <- c(TRUE, FALSE, NA, TRUE, FALSE))
names(df2) <- c("No.","Letters","Complex","Logical")
df2
df2[df2 == 99] <- NA; df2 # replace values of 99 or more to be NA
dt1[is.na(dt1)] <- 100 # replace NA values with 100
dt1
dt2 <- dt$Weight
dt2[is.na(dt2)] <- mean(dt2, na.rm=TRUE) # replace NA values with mean
dt2; is.na(dt2); sum(is.na(dt2))
```
2.8(c)
```{r}
z1 <- c(15:20, NA, 13.8, NA); z1
mean(z1) # find mean and include NA in the data
mean(z1, na.rm=TRUE) # Exclude NA values
# data frame with missing values
df3 <- data.frame(x1 <- c(15, 5, 10, NA, 25),
x2 <- c("T", "E", "S", "T", NA),
x3 <- c(1+5i, 2-3i, NA, NA, 3.5),
x4 <- c(TRUE, FALSE, NA, TRUE, FALSE))
names(df3) <- c("No.","Letters","Complex","Logical")
df3
# identify complete cases in data frame
df3[complete.cases(df3), ]
na.omit(df3)
# identify incomplete cases using ’i’ operator
df3[ !complete.cases(df3),]
```
2.9
```{r}
## filter(.)
library(dplyr)
library(datasets)
titanic <- data.frame(Titanic)
titanic
head(titanic); tail(titanic)
filter(titanic, Sex == "Male")
titanic_pct <- titanic$Freq/(sum(titanic$Freq))*100
titanic_new <- cbind(titanic,round(titanic_pct,2))
titanic_new
sum(titanic_new$'round(titanic_pct, 2)')
```
2.10
```{r}
## If the remaider is zero, the number is ‘Even"
## Else the number is ‘Odd’
## Using ‘ifelse’ function
v1 <- 1:10
ifelse(v1 %% 2 == 0, "Even", "Odd")
## ------------------------------------ ##
## Using Looping ‘if’ and ‘else’
result <- c()
v1 <- 1:10
for (x in v1){
if (x %% 2 == 0)
{result <- c(result, "Even")}
else
{result <- c(result, "Odd")}
}
result
```



