---
title: "R Notebook"
output: html_notebook
---
Example 7.1 Return Function for One Value
```{r}
## Return one value
func_1 <- function(x, y)
{ z <- x*y -3*y
return(z)}
func_1(2,6) #call function
```
```{r}
#without return
func_2 <- function(x, y)
{ z <- x*y -3*y
z}
func_2(2,6) #call function
```
Example 7.2 Return Function for Multiple Values Using
Lists
```{r}
func_3 <- function(x, y)
{ z1 <- x*y -3*y
z2 <- x + y
z3 <- x/y
return(list(z1,z2,z3))
}
func_3(2,6)
```
Example 7.3a Built-in Functions
```{r}
## Built-in function
dt <- mtcars
head(dt); tail(dt)
```
```{r}
str(dt); names(dt) # variable name
```
```{r}
class(dt); attributes(dt)
length(dt) #no. of variables
dim(dt)
summary(dt) #descriptive statistics
```
```{r}
dt1 <- dt[,c(1,3,6)]
head(dt1)
tail(dt1)
```
```{r}
summary(dt1) #descriptive statistics
```

```{r}
library(psych)
describe(dt1) #descriptive statistics
plot(dt1$mpg); plot(dt1$disp); plot(dt1$wt)
hist(dt1$mpg); hist(dt1$disp); hist(dt1$wt)
```
Example 7.4 User-defined Functions
```{r}
func_3 <- function(x, y)
{ z1 <- x*y -3*y
z2 <- x + y
z3 <- x/y
return(list(z1,z2,z3))
}
func_3(2,6)
##----------------------
## Volume of cylinder
vol_cyl <- function(r,h)
{ base <- pi*r^2
vol <- base*h
vol
}
vol_cyl(5,10)

```
Example 7.5 Top Level Environment
```{r}
# To clear global workspace
rm(list = ls())
# Example
x <- 12
f1 <- function(y) {
w <- 8
f2 <- function() {
return(2*w/(x+y))
}
return(f2())
}
environment(f1)
ls()
ls.str() # more information
f1(3)
```
Example 7.6a No pointer in R
```{r}
#In Python:
>>> x = [14, 2, 20]
>>> x.sort()
>>> x
[2,14,20]
#In R:
> x <- c(14, 2, 20)
> sort(x)
[1] 2 14 20
> x
[1] 14 2 20
x <- sort(x)
x
[1] 2 14 20

```
Example 7.6b No pointer in R
```{r}
odd_even <- function(w)
{ odd <- which(w %% 2 == 1)
even <- which(w %% 2 == 0)
list(od =odd , ev =even)
}
w <- seq(1,20, by=1)
odd_even(w)

```

